# Faça um programa que leia um número inteiro qualquer e mostre sua tabuada.
n1 = int(input('Escolha um número para saber sua tabuada do 1 ao 10: '))
print('A tabuada de {} é:'.format(n1))
print('='*20)
print('1  x  {} = {} '.format(n1, n1*1))
print('2  x  {} = {} '.format(n1, n1*2))
print('3  x  {} = {} '.format(n1, n1*3))
print('4  x  {} = {} '.format(n1, n1*4))
print('5  x  {} = {} '.format(n1, n1*5))
print('6  x  {} = {} '.format(n1, n1*6))
print('7  x  {} = {} '.format(n1, n1*7))
print('8  x  {} = {} '.format(n1, n1*8))
print('9  x  {} = {} '.format(n1, n1*9))
print('10 x  {} = {} '.format(n1, n1*10))
print('='*20)
